### ISSUE TITLE
Issue with cmdlnprint in OS X

### ISSUE THREAD

**Issue by sbrudz** [eclipxe13/cmdlnprint#5]
Hello,

I'm excited to use your extension but it doesn't seem to be working properly for me.  

When I try it in OS X 10.11.6, Firefox starts up and loads the page, but nothing is printed and the browser window stays open.

Here's the command I'm using:

``` sh
/Applications/Firefox.app/Contents/MacOS/firefox -print https://google.com -print-mode pdf -print-file /Users/myaccount/test.pdf
```

I've tried running it with Firefox 49.0.1 and Firefox 45.4.0 but the same thing happens.

I've also tried Ubuntu 14.04 and get almost the same issue.

Can you provide any pointers to help me get this working?

Thank you,

Steve

**Comment by eclipxe13** [comment]
I will put a VirtualBox machine with Ubuntu 16.04 and firefox and see what is going on.
I try with command without any error (just change the path for firefox and the result file to /tmp/test.pdf)
Let me check and I will back to you.

**Comment by eclipxe13** [comment]
OK, I follow this steps:
1. Run the ubuntu 16.04 livecd using virtualbox
2. Upgrade firefox `sudo apt-get update && sudo apt-get install firefox`
3. Open mozilla and install plugin (require firefox restart)
4. Run command `firefox -print https://google.com -print-mode pdf -print-file /tmp/test.pdf`

It worked fine.

Could you please make some tests for me:
- Be sure that the destination file is a full path, the folder exists, the file name does not exists and you have permissions to write on destination.
- Check that you can create a PDF file as user (open firefox, open url, print, print to file, set a filename and options, save it, review it)
- Run the command using -jsconsole `firefox -jsconsole -print http://...`, this would give me some hints about where the problem is.

I don't want this to be a "this is working on my machine" thing, let's see what is going on.

**Comment by eclipxe13** [comment]
BTW, I try it using firefox versions 49.0+build4-0ubuntu0.16.04.1 and 45.0.2+build1-0ubuntu1

**Comment by sbrudz** [comment]
Thank you for your swift response.  I was able to get it working with a fresh install of 16.04 following the steps you outlined.

On ubuntu 14.04 it still didn't work.  The only error in the jsconsole was:

```
Could not read chrome manifest
```

On OS X, the errors in the jsconsole were:

```
Could not read chrome manifest 'file:///Applications/Firefox.app/Contents/Resources/chrome.manifest'.

NS_ERROR_FACTORY_NOT_REGISTERED: Component returned failure code: 0x80040154  mininav.js:332
(NS_ERROR_FACTORY_NOT_REGISTERED) [nsIPrintSettingsService.defaultPrinterName]
delayedPrintPageLoadComplete() mininav.js:332
onPrintPageLoadComplete() mininav.js:185
onDocumentReadyStateChange() mininav.js:178
```

Ubuntu 16.04 seems like the way to go.  Thanks again.

**Comment by cosmo0920** [comment]
I've tried on macOS 10.12.2 but it doesn't seem to be not work properly for me.
So, I investigate why does not work on macOS.

In almost all platform, Firefox can register print progress listener here: https://dxr.mozilla.org/mozilla-release/source/layout/printing/nsPrintEngine.cpp#1070

In "Almost all platform", Firefox can create and register print progress:
https://dxr.mozilla.org/mozilla-release/search?q=nsPrintingPromptService%3A%3AShowProgress

But I'm surprisingly, in macOS, Firefox does not implement this feature: 
https://dxr.mozilla.org/mozilla-release/source/embedding/components/printingui/mac/nsPrintingPromptServiceX.mm#67

Is there way to obtain Web pages as PDF on macOS with this addon?

**Comment by bdurrow** [comment]
I tried Ubuntu 16.04 with 45.0.2+build1-0ubuntu1 and found prints are not made.  I had originally tried centos6 and centos7 with ff45 with the same problem but tried ubuntu after @eclipxe13 said it worked.

**Comment by eclipxe13** [comment]
@cosmo0920 I will remove the compatibility of this plugin on mac. Thanks for your links, it make a detailed identification of why this fail on mac. Unfortunately I don't have a mac to test.

**Comment by eclipxe13** [comment]
@bdurrow Are you reporting that the plugin is not working on ubuntu 16.04?
If so, could you please follow the steps on https://github.com/eclipxe13/cmdlnprint/issues/5#issuecomment-252497276 and tell me is this is failing on a new ticket? I will close this issue.
